#!/data/data/com.termux/files/usr/bin/bash
# ╔══════════════════════════════════════════════════════════════╗
# ║   LANIAKEA COMPOSITE METAVERSE — FULL AUTO SYSTEM          ║
# ║   Self-Write · Self-Install · Self-Diagnose · Self-Heal    ║
# ║   One script. Paste once. Everything runs automatically.   ║
# ╚══════════════════════════════════════════════════════════════╝
# Usage: bash laniakea-auto.sh
# Or paste the one-liner from GitHub into Termux directly.

set -euo pipefail

# ── Constants ─────────────────────────────────────────────────
DIR="$HOME/laniakea"
SERVER="$DIR/laniakea-server.js"
WATCHDOG="$DIR/watchdog.sh"
DIAG="$DIR/diagnostics.sh"
LOG="$DIR/server.log"
WLOG="$DIR/watchdog.log"
PIDFILE="$DIR/server.pid"
PORT=3000
HEALTH_URL="http://127.0.0.1:${PORT}/api/health"
REPO="https://github.com/shalominattii-us/SOVEREIGN-INTERFACE-.git"
REPO_DIR="$HOME/sovereign-interface"

# ── Colors ────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

banner() {
  echo -e "${CYAN}"
  echo "╔══════════════════════════════════════════════════════════╗"
  echo "║   LANIAKEA COMPOSITE METAVERSE — AUTO SYSTEM v2.0      ║"
  echo "╚══════════════════════════════════════════════════════════╝"
  echo -e "${RESET}"
}

log()  { echo -e "${GREEN}[✓]${RESET} $*"; }
warn() { echo -e "${YELLOW}[!]${RESET} $*"; }
err()  { echo -e "${RED}[✗]${RESET} $*"; }
step() { echo -e "${BOLD}${CYAN}━━ $* ${RESET}"; }

# ════════════════════════════════════════════════════════════════
# PHASE 1 — ENVIRONMENT SETUP
# ════════════════════════════════════════════════════════════════
banner
step "PHASE 1: Environment Setup"

mkdir -p "$DIR"

# Install Node.js if missing
if ! command -v node &>/dev/null; then
  warn "Node.js not found — installing..."
  pkg update -y && pkg install -y nodejs
  log "Node.js installed: $(node --version)"
else
  log "Node.js already installed: $(node --version)"
fi

# Install npm deps if missing
if [ ! -d "$DIR/node_modules/express" ]; then
  step "Installing npm dependencies..."
  cd "$DIR"
  npm install --save express @trpc/server zod 2>&1 | tail -3
  log "Dependencies installed"
else
  log "Dependencies already present"
fi

# ════════════════════════════════════════════════════════════════
# PHASE 2 — SELF-WRITE SERVER CODE
# ════════════════════════════════════════════════════════════════
step "PHASE 2: Self-Writing Server Code"

cat > "$SERVER" << 'SERVEREOF'
#!/usr/bin/env node
/**
 * LANIAKEA COMPOSITE METAVERSE — Standalone Backend Server
 * Auto-generated by laniakea-auto.sh
 * Self-writing · Self-healing · Full tRPC API
 */
const express = require("express");
const { initTRPC } = require("@trpc/server");
const { createExpressMiddleware } = require("@trpc/server/adapters/express");
const { z } = require("zod");
const os = require("os");
const fs = require("fs");
const path = require("path");

const t = initTRPC.create();
const router = t.router;
const publicProcedure = t.procedure;

// ── Data Generators ───────────────────────────────────────────
function getClusters() {
  return [
    { id:"c1", name:"Primary AWS US-East",    status:"active",  type:"primary",   region:"us-east-1",       provider:"AWS",   nodeCount:12, cpuUsage:34, memoryUsage:52, version:"1.29.0" },
    { id:"c2", name:"Primary Azure EU-West",  status:"active",  type:"primary",   region:"westeurope",      provider:"Azure", nodeCount:8,  cpuUsage:28, memoryUsage:45, version:"1.29.0" },
    { id:"c3", name:"Secondary AWS US-West",  status:"standby", type:"secondary", region:"us-west-2",       provider:"AWS",   nodeCount:6,  cpuUsage:12, memoryUsage:30, version:"1.29.0" },
    { id:"c4", name:"Secondary GCP Asia SE",  status:"standby", type:"secondary", region:"asia-southeast1", provider:"GCP",   nodeCount:6,  cpuUsage:10, memoryUsage:28, version:"1.29.0" },
    { id:"c5", name:"Edge K3s On-Premises",   status:"active",  type:"edge",      region:"on-premises",     provider:"K3s",   nodeCount:4,  cpuUsage:55, memoryUsage:68, version:"1.28.5" },
    { id:"c6", name:"DR AWS EU-Central",      status:"standby", type:"dr",        region:"eu-central-1",    provider:"AWS",   nodeCount:4,  cpuUsage:8,  memoryUsage:22, version:"1.29.0" },
  ];
}
function getServices() {
  return [
    { id:"s1", name:"WebXR Gateway",  status:"running", type:"gateway",  replicas:3, cpu:22, memory:41, uptime:99.97 },
    { id:"s2", name:"Spatial Sync",   status:"running", type:"sync",     replicas:5, cpu:38, memory:55, uptime:99.95 },
    { id:"s3", name:"Avatar Service", status:"running", type:"avatar",   replicas:4, cpu:29, memory:48, uptime:99.99 },
    { id:"s4", name:"World State DB", status:"running", type:"database", replicas:3, cpu:45, memory:72, uptime:100.0 },
  ];
}
function getAlerts() {
  const now = Date.now();
  return [
    { id:"a1", severity:"info",    message:"Edge cluster CPU at 55% — within normal range",  service:"Edge K3s",      timestamp:new Date(now-3600000)  },
    { id:"a2", severity:"warning", message:"World State DB memory at 72% — monitor closely", service:"World State DB", timestamp:new Date(now-7200000)  },
    { id:"a3", severity:"info",    message:"Spatial Sync replicas scaled to 5 successfully", service:"Spatial Sync",  timestamp:new Date(now-14400000) },
  ];
}
function getMetrics() {
  const now = Date.now();
  return Array.from({length:24},(_,i)=>({
    timestamp:new Date(now-(23-i)*3600000),
    cpu:20+Math.random()*40, memory:35+Math.random()*30,
    requestLatency:80+Math.random()*60, requestRate:800+Math.random()*400, errorRate:Math.random()*0.5,
  }));
}
function getLogs() {
  const now=Date.now(), levels=["info","info","warn","error"], services=["WebXR Gateway","Spatial Sync","Avatar Service","World State DB"];
  const msgs=["Request processed","WebSocket connected","Sync checkpoint done","Avatar serialized","Memory above 70%","Retry 1/3","Connection timeout"];
  return Array.from({length:20},(_,i)=>({ id:`log-${i+1}`, level:levels[Math.floor(Math.random()*levels.length)], service:services[Math.floor(Math.random()*services.length)], message:msgs[Math.floor(Math.random()*msgs.length)], timestamp:new Date(now-i*180000) }));
}
function getTraces() {
  const now=Date.now(), svcs=["WebXR Gateway","Spatial Sync","Avatar Service"];
  return Array.from({length:15},(_,i)=>({ id:`trace-${i+1}`, service:svcs[i%svcs.length], status:Math.random()>0.1?"success":"error", duration:50+Math.random()*200, timestamp:new Date(now-i*120000) }));
}

// ── tRPC Router ───────────────────────────────────────────────
const appRouter = router({
  laniakea: router({
    getDashboardSummary: publicProcedure.query(()=>{
      const clusters=getClusters(), services=getServices(), alerts=getAlerts();
      const activeClusters=clusters.filter(c=>c.status==="active").length;
      const totalNodes=clusters.reduce((s,c)=>s+c.nodeCount,0);
      const avgCpu=Math.round(clusters.reduce((s,c)=>s+c.cpuUsage,0)/clusters.length);
      const avgMem=Math.round(clusters.reduce((s,c)=>s+c.memoryUsage,0)/clusters.length);
      const running=services.filter(s=>s.status==="running").length;
      let health="healthy"; if(avgCpu>80||avgMem>80) health="critical"; else if(avgCpu>70||avgMem>70) health="warning";
      return {overallHealth:health,activeClusters,totalNodes,avgCpuUsage:avgCpu,avgMemoryUsage:avgMem,runningServices:running,totalServices:services.length,recentAlerts:alerts.slice(0,5)};
    }),
    getClusters:    publicProcedure.query(()=>getClusters()),
    getCluster:     publicProcedure.input(z.object({id:z.string()})).query(({input})=>{ const c=getClusters().find(c=>c.id===input.id); if(!c) throw new Error("Not found"); return c; }),
    getServices:    publicProcedure.query(()=>getServices()),
    getAlerts:      publicProcedure.query(()=>getAlerts()),
    getMetrics:     publicProcedure.query(()=>getMetrics()),
    getLogs:        publicProcedure.query(()=>getLogs()),
    getTraces:      publicProcedure.query(()=>getTraces()),
    getFailoverStatus: publicProcedure.query(()=>({ primaryCluster:"Primary AWS US-East", secondaryCluster:"Secondary AWS US-West", primaryReadiness:100, secondaryReadiness:98, lastFailover:new Date(Date.now()-86400000*14), history:[] })),
    initiateFailover:  publicProcedure.input(z.object({fromCluster:z.string(),toCluster:z.string()})).mutation(({input})=>({ success:true, message:`Failover: ${input.fromCluster} → ${input.toCluster}`, estimatedDuration:300, timestamp:new Date() })),
    getDeploymentStatus: publicProcedure.query(()=>({ currentPhase:"Operational", phases:[{id:"p1",name:"Infrastructure",status:"completed"},{id:"p2",name:"Cluster Federation",status:"completed"},{id:"p3",name:"Service Mesh",status:"completed"},{id:"p4",name:"Metaverse Services",status:"completed"},{id:"p5",name:"Observability",status:"completed"}], history:[] })),
    startDeployment: publicProcedure.mutation(()=>({ success:true, deploymentId:`dep-${Date.now()}`, message:"Pipeline initiated", timestamp:new Date() })),
  })
});

// ── Express App ───────────────────────────────────────────────
const app = express();
app.use((req,res,next)=>{
  const origin=req.headers.origin||"*";
  res.header("Access-Control-Allow-Origin",origin);
  res.header("Access-Control-Allow-Methods","GET,POST,PUT,DELETE,OPTIONS");
  res.header("Access-Control-Allow-Headers","Origin,X-Requested-With,Content-Type,Accept,Authorization");
  res.header("Access-Control-Allow-Credentials","true");
  if(req.method==="OPTIONS"){res.sendStatus(200);return;}
  next();
});
app.use(express.json({limit:"10mb"}));

// Health endpoint
app.get("/api/health",(req,res)=>{
  const uptime=process.uptime();
  res.json({ ok:true, status:"healthy", service:"laniakea-backend", uptime:Math.round(uptime), uptimeHuman:`${Math.floor(uptime/3600)}h ${Math.floor((uptime%3600)/60)}m ${Math.floor(uptime%60)}s`, timestamp:Date.now(), version:"2.0.0", pid:process.pid });
});

// Diagnostics endpoint
app.get("/api/diagnostics",(req,res)=>{
  const mem=process.memoryUsage();
  const ifaces=os.networkInterfaces();
  const ips=[];
  for(const name of Object.keys(ifaces)) for(const i of ifaces[name]) if(i.family==="IPv4"&&!i.internal) ips.push({name,address:i.address});
  res.json({
    ok:true, timestamp:Date.now(), pid:process.pid,
    node:process.version, platform:process.platform, arch:process.arch,
    uptime:Math.round(process.uptime()),
    memory:{ rss:`${Math.round(mem.rss/1024/1024)}MB`, heap:`${Math.round(mem.heapUsed/1024/1024)}/${Math.round(mem.heapTotal/1024/1024)}MB` },
    network:ips,
    endpoints:["/api/health","/api/diagnostics","/api/trpc/laniakea.getDashboardSummary","/api/trpc/laniakea.getClusters","/api/trpc/laniakea.getServices","/api/trpc/laniakea.getAlerts","/api/trpc/laniakea.getMetrics","/api/trpc/laniakea.getLogs","/api/trpc/laniakea.getTraces","/api/trpc/laniakea.getFailoverStatus","/api/trpc/laniakea.getDeploymentStatus"],
  });
});

app.use("/api/trpc",createExpressMiddleware({router:appRouter,createContext:()=>({})}));

// ── Start ─────────────────────────────────────────────────────
const PORT=parseInt(process.env.PORT||"3000",10);
function getLocalIP(){
  const ifaces=os.networkInterfaces();
  for(const name of Object.keys(ifaces)) for(const i of ifaces[name]) if(i.family==="IPv4"&&!i.internal) return i.address;
  return "127.0.0.1";
}
const localIP=getLocalIP();

// Write PID file
fs.writeFileSync(path.join(__dirname,"server.pid"),String(process.pid));

app.listen(PORT,"0.0.0.0",()=>{
  console.log("");
  console.log("╔══════════════════════════════════════════════════════════╗");
  console.log("║   LANIAKEA COMPOSITE METAVERSE — SERVER READY v2.0     ║");
  console.log("╚══════════════════════════════════════════════════════════╝");
  console.log("");
  console.log(`  ✅  PID          : ${process.pid}`);
  console.log(`  ✅  Port         : ${PORT}`);
  console.log(`  📱  Loopback     : http://127.0.0.1:${PORT}`);
  console.log(`  🌐  Network      : http://${localIP}:${PORT}`);
  console.log(`  🔍  Health       : http://127.0.0.1:${PORT}/api/health`);
  console.log(`  🩺  Diagnostics  : http://127.0.0.1:${PORT}/api/diagnostics`);
  console.log("");
  console.log("  EXPO_PUBLIC_API_BASE_URL=http://127.0.0.1:" + PORT);
  console.log("");
  console.log("  Watchdog is monitoring — auto-restarts on crash.");
  console.log("─────────────────────────────────────────────────────────");
});

process.on("uncaughtException",(err)=>{ console.error("[CRASH]",err.message); process.exit(1); });
process.on("unhandledRejection",(err)=>{ console.error("[REJECT]",err); process.exit(1); });
SERVEREOF

log "Server code written to $SERVER"

# ════════════════════════════════════════════════════════════════
# PHASE 3 — SELF-WRITE WATCHDOG (Self-Healing)
# ════════════════════════════════════════════════════════════════
step "PHASE 3: Self-Writing Watchdog (Self-Healing)"

cat > "$WATCHDOG" << WDEOF
#!/data/data/com.termux/files/usr/bin/bash
# LANIAKEA WATCHDOG — Auto-restart on crash
# Self-healing: monitors health endpoint, restarts if down
DIR="$DIR"
SERVER="$SERVER"
LOG="$LOG"
PIDFILE="$PIDFILE"
PORT=$PORT
HEALTH="http://127.0.0.1:\${PORT}/api/health"
MAX_RESTARTS=10
restarts=0

echo "[WATCHDOG] Started at \$(date)" >> "$WLOG"

while true; do
  # Check if server is alive via health endpoint
  if curl -sf "\$HEALTH" > /dev/null 2>&1; then
    # Server healthy — reset restart counter
    restarts=0
    sleep 10
    continue
  fi

  # Server is down
  restarts=\$((restarts+1))
  echo "[WATCHDOG] \$(date) — Server down. Restart #\$restarts" >> "$WLOG"

  if [ \$restarts -ge \$MAX_RESTARTS ]; then
    echo "[WATCHDOG] \$(date) — Max restarts reached. Waiting 60s before retry." >> "$WLOG"
    restarts=0
    sleep 60
  fi

  # Kill any zombie process on port
  fuser -k \${PORT}/tcp 2>/dev/null || true
  sleep 2

  # Restart server
  cd "\$DIR"
  nohup node "\$SERVER" >> "\$LOG" 2>&1 &
  echo \$! > "\$PIDFILE"
  echo "[WATCHDOG] \$(date) — Server restarted. PID: \$!" >> "$WLOG"
  sleep 5
done
WDEOF

chmod +x "$WATCHDOG"
log "Watchdog written to $WATCHDOG"

# ════════════════════════════════════════════════════════════════
# PHASE 4 — SELF-WRITE DIAGNOSTICS SCRIPT
# ════════════════════════════════════════════════════════════════
step "PHASE 4: Self-Writing Diagnostics Script"

cat > "$DIAG" << DIAGEOF
#!/data/data/com.termux/files/usr/bin/bash
# LANIAKEA DIAGNOSTICS — Full system health confirmation
PORT=$PORT
HEALTH="http://127.0.0.1:\${PORT}/api/health"
DIAG_URL="http://127.0.0.1:\${PORT}/api/diagnostics"

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║   LANIAKEA DIAGNOSTICS — HEALTH CONFIRMATION           ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

# 1. Process check
PID=\$(cat "$PIDFILE" 2>/dev/null || echo "")
if [ -n "\$PID" ] && kill -0 "\$PID" 2>/dev/null; then
  echo "  ✅  Process     : RUNNING (PID \$PID)"
else
  echo "  ❌  Process     : NOT RUNNING"
fi

# 2. Port check
if fuser \${PORT}/tcp > /dev/null 2>&1; then
  echo "  ✅  Port \${PORT}    : OPEN"
else
  echo "  ❌  Port \${PORT}    : CLOSED"
fi

# 3. Health endpoint
HEALTH_RESP=\$(curl -sf --max-time 5 "\$HEALTH" 2>/dev/null)
if [ -n "\$HEALTH_RESP" ]; then
  UPTIME=\$(echo "\$HEALTH_RESP" | grep -o '"uptimeHuman":"[^"]*"' | cut -d'"' -f4)
  echo "  ✅  Health API  : OK (uptime: \$UPTIME)"
else
  echo "  ❌  Health API  : UNREACHABLE"
fi

# 4. Diagnostics endpoint
DIAG_RESP=\$(curl -sf --max-time 5 "\$DIAG_URL" 2>/dev/null)
if [ -n "\$DIAG_RESP" ]; then
  MEM=\$(echo "\$DIAG_RESP" | grep -o '"rss":"[^"]*"' | cut -d'"' -f4)
  echo "  ✅  Diagnostics : OK (memory: \$MEM)"
else
  echo "  ❌  Diagnostics : UNREACHABLE"
fi

# 5. tRPC dashboard check
TRPC_RESP=\$(curl -sf --max-time 5 "http://127.0.0.1:\${PORT}/api/trpc/laniakea.getDashboardSummary?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%7D%7D" 2>/dev/null)
if [ -n "\$TRPC_RESP" ]; then
  HEALTH_STATUS=\$(echo "\$TRPC_RESP" | grep -o '"overallHealth":"[^"]*"' | cut -d'"' -f4)
  CLUSTERS=\$(echo "\$TRPC_RESP" | grep -o '"activeClusters":[0-9]*' | cut -d':' -f2)
  SERVICES=\$(echo "\$TRPC_RESP" | grep -o '"runningServices":[0-9]*' | cut -d':' -f2)
  echo "  ✅  Dashboard   : OK (health=\$HEALTH_STATUS, clusters=\$CLUSTERS, services=\$SERVICES)"
else
  echo "  ❌  Dashboard   : UNREACHABLE"
fi

# 6. Network IP
LOCAL_IP=\$(hostname -I | awk '{print \$1}')
echo ""
echo "  📱  Loopback    : http://127.0.0.1:\${PORT}"
echo "  🌐  Network     : http://\${LOCAL_IP}:\${PORT}"
echo ""
echo "  EXPO_PUBLIC_API_BASE_URL=http://127.0.0.1:\${PORT}"
echo ""
echo "  Watchdog log   : tail -f $WLOG"
echo "  Server log     : tail -f $LOG"
echo ""
DIAGEOF

chmod +x "$DIAG"
log "Diagnostics script written to $DIAG"

# ════════════════════════════════════════════════════════════════
# PHASE 5 — KILL ANY EXISTING SERVER, START FRESH
# ════════════════════════════════════════════════════════════════
step "PHASE 5: Starting Server"

# Kill anything on port 3000
fuser -k ${PORT}/tcp 2>/dev/null || true
sleep 1

# Start server in background
cd "$DIR"
nohup node "$SERVER" >> "$LOG" 2>&1 &
SERVER_PID=$!
echo $SERVER_PID > "$PIDFILE"
log "Server started (PID $SERVER_PID)"

# Wait for it to be ready
echo -n "  Waiting for server to be ready"
for i in $(seq 1 15); do
  sleep 1
  echo -n "."
  if curl -sf "$HEALTH_URL" > /dev/null 2>&1; then
    echo ""
    log "Server is UP and healthy"
    break
  fi
  if [ $i -eq 15 ]; then
    echo ""
    err "Server did not respond in 15s — check log: $LOG"
    tail -20 "$LOG"
    exit 1
  fi
done

# ════════════════════════════════════════════════════════════════
# PHASE 6 — START WATCHDOG
# ════════════════════════════════════════════════════════════════
step "PHASE 6: Starting Watchdog (Self-Healing)"

# Kill any existing watchdog
pkill -f "watchdog.sh" 2>/dev/null || true
sleep 1

nohup bash "$WATCHDOG" >> "$WLOG" 2>&1 &
WATCHDOG_PID=$!
log "Watchdog started (PID $WATCHDOG_PID)"

# ════════════════════════════════════════════════════════════════
# PHASE 7 — FULL DIAGNOSTIC CONFIRMATION
# ════════════════════════════════════════════════════════════════
step "PHASE 7: Running Full Diagnostic Confirmation"
sleep 2
bash "$DIAG"

# ════════════════════════════════════════════════════════════════
# DONE
# ════════════════════════════════════════════════════════════════
LOCAL_IP=$(hostname -I | awk '{print $1}')
echo -e "${GREEN}${BOLD}"
echo "╔══════════════════════════════════════════════════════════╗"
echo "║   ✅  LANIAKEA AUTO SYSTEM — FULLY OPERATIONAL         ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo -e "${RESET}"
echo "  Server PID   : $SERVER_PID"
echo "  Watchdog PID : $WATCHDOG_PID"
echo "  API URL      : http://127.0.0.1:${PORT}"
echo "  Network URL  : http://${LOCAL_IP}:${PORT}"
echo ""
echo "  To check health anytime:"
echo "    bash $DIAG"
echo ""
echo "  To view logs:"
echo "    tail -f $LOG"
echo ""
echo "  The watchdog will auto-restart the server if it crashes."
echo "  Both processes survive Termux session — safe to minimize."
echo ""
