#!/data/data/com.termux/files/usr/bin/bash
# ============================================================
#  LANIAKEA BACKEND SERVER — Start Script for Termux
#  Starts the API server and prints the local IP + QR code
# ============================================================

set -e

LANIAKEA_DIR="$HOME/sovereign-interface/LANIAKEA"

# ── Check that the build exists ───────────────────────────
if [ ! -f "$LANIAKEA_DIR/dist/index.js" ]; then
  echo "❌  Server not built. Run setup.sh first:"
  echo "   bash ~/sovereign-interface/LANIAKEA/setup.sh"
  exit 1
fi

# ── Get local IP address ──────────────────────────────────
LOCAL_IP=$(ip route get 1.1.1.1 2>/dev/null | grep -oP 'src \K\S+' || hostname -I | awk '{print $1}')
PORT=3000
API_URL="http://${LOCAL_IP}:${PORT}"

echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║     LANIAKEA COMPOSITE METAVERSE — Starting      ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""
echo "  Local IP  : $LOCAL_IP"
echo "  Port      : $PORT"
echo "  API URL   : $API_URL"
echo ""
echo "  ⚠  Make sure your phone and PC are on the same WiFi"
echo "     OR use the loopback address: http://127.0.0.1:$PORT"
echo "     (loopback works if the app runs on the same device)"
echo ""

# ── Write .env so the app picks up the URL ───────────────
cat > "$LANIAKEA_DIR/.env" << EOF
# Auto-generated by termux-start.sh
EXPO_PUBLIC_API_BASE_URL=http://${LOCAL_IP}:${PORT}
NODE_ENV=production
EOF

echo "  .env written with EXPO_PUBLIC_API_BASE_URL=$API_URL"
echo ""
echo "  Starting server... (Ctrl+C to stop)"
echo "─────────────────────────────────────────────────────"

# ── Start the server ──────────────────────────────────────
cd "$LANIAKEA_DIR"
NODE_ENV=production node dist/index.js
